language: node_js
node_js:
  - "8.11.1"

branches:
  only:
    - master
    - staging

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - cd functions && npm install && npm run build
  - cd ..

script:
  - npm run lint
  - if [ $TRAVIS_BRANCH = master ]; then npm run build:prod; fi
  - if [ $TRAVIS_BRANCH = staging ]; then npm run build; fi

before_deploy:

deploy:
  skip_cleanup: true
  - provider: firebase
    token: $FIREBASE_TOKEN
    on:
      branch: master
  - provider: firebase
    project: staging
    token: $FIREBASE_TOKEN_STAGING
    on:
      branch: staging

notifications:
  email:
    on_failure: change
    on_success: change
