language: node_js
# use version in `.nvmrc`
node_js:
cache:
  directories:
    - node_modules

branches:
  only:
    - master
    - staging

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - npm run build:functions
  - npm run lint
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run build:prod; fi
  - if [ "$TRAVIS_BRANCH" == "staging" ]; then npm run build; fi

deploy:
  # production deployment
  - provider: firebase
    project: "default"
    token: $FIREBASE_TOKEN
    skip_cleanup: true
    on:
      branch: master
  # staging deployment
  - provider: firebase
    project: "staging"
    token: $FIREBASE_TOKEN_STAGING
    skip_cleanup: true
    on:
      branch: staging

notifications:
  email:
    on_failure: change
    on_success: change
