language: node_js
# use version in `.nvmrc`
node_js:
cache:
  directories:
    - node_modules

branches:
  only:
  - master
  - staging

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm run build:functions

script:
  - npm run lint
  - if [ branch = master ]; then npm run build:prod; fi
  - if [ branch = staging ]; then npm run build; fi

deploy:
  skip_cleanup: true
  # production deployment
  - provider: firebase
    token: $FIREBASE_TOKEN
    on:
      branch: master
  # staging deployment
  - provider: firebase
    project: staging
    token: $FIREBASE_TOKEN_STAGING
    on:
      branch: staging

notifications:
  email:
    on_failure: change
    on_success: change
